# Custom RDS module - private PostgreSQL database.
# Key private-connectivity design points (see also docs in root README):
#   1) DB subnet group uses ONLY private subnets - no public subnet, no
#      public IP possible.
#   2) publicly_accessible = false - AWS refuses to attach a public IP
#      even if someone later mis-configures the subnet.
#   3) Security group ingress allows port 5432 ONLY from the EKS node
#      security group - nothing else in or outside the VPC can connect.
#   4) The real password never lives in Terraform state in plaintext for
#      long: it's generated once, stored in Secrets Manager, and Terraform
#      only ever writes/reads the Secrets Manager reference.

resource "aws_db_subnet_group" "this" {
  name       = "devops-assessment-db-subnets"
  subnet_ids = var.private_subnet_ids

  tags = { Name = "devops-assessment-db-subnets" }
}

resource "aws_security_group" "db" {
  name_prefix = "devops-assessment-db-sg-"
  vpc_id      = var.vpc_id

  # Only traffic from EKS worker nodes (i.e. backend pods) may reach the DB port.
  ingress {
    description     = "Postgres from EKS nodes only"
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [var.allowed_security_group_id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "devops-assessment-db-sg" }
}

# Password is generated by Terraform once, then stored in Secrets Manager.
# Terraform state will contain it (state should always be encrypted +
# access-restricted, per provider.tf backend config) but application code
# and CI/CD never see it directly - they read it from Secrets Manager.
resource "random_password" "db" {
  length  = 24
  special = false
}

resource "aws_secretsmanager_secret" "db" {
  name = "devops-assessment/${var.environment}/db-credentials"
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    dbname   = var.db_name
  })
}

resource "aws_db_instance" "this" {
  identifier     = "devops-assessment-${var.environment}"
  engine         = "postgres"
  engine_version = "16.3"
  instance_class = var.db_instance_class

  allocated_storage = 20
  storage_encrypted = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.db.id]

  # Core private-connectivity requirement: no public IP, ever.
  publicly_accessible = false

  multi_az                = var.environment == "production"
  backup_retention_period = 7
  skip_final_snapshot     = var.environment != "production"
  deletion_protection     = var.environment == "production"

  tags = { Name = "devops-assessment-${var.environment}-db" }
}

# Private DNS record so the backend connects via a stable hostname
# (e.g. db.internal.local) instead of a raw RDS endpoint that could
# change on failover.
resource "aws_route53_record" "db" {
  zone_id = var.private_zone_id
  name    = "db.internal.local"
  type    = "CNAME"
  ttl     = 60
  records = [aws_db_instance.this.address]
}
